#!/bin/bash

echo "client machine"

#ssh -i "carbanaktest2.pem" kali@ec2-35-171-225-42.compute-1.amazonaws.com 
#'bash -s' << 'ENDSSH'
 # echo "test"
 # cd /home/
 pwd
#ENDSSH
echo "connecting to client machine..."
ssh kali@10.0.2.15 << 'ENDSSH'
  echo "connected to client"
  ./payload.bin
  echo "done"
  echo "exiting"
  exit
ENDSSH


